_target_: src.arcane2.models.resunetplusplus.ResUNet
input_channels: 8
input_length: ${base_dataset.n_samples}
n_filters:
  - 0
  - 16
  - 32
  - 64
  - 128
  - 256
num_classes: 2
output_length: ${base_dataset.n_samples}
activation: "softmax"
