name: lightning-arcane-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip=24.3.1
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - attrs==23.2.0
      - certifi==2024.6.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.2.1
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - fastdtw==0.3.4
      - filelock==3.14.0
      - fonttools==4.53.0
      - frozenlist==1.4.1
      - fsspec==2024.6.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - grpcio==1.64.1
      - hydra-core==1.3.2
      - idna==3.7
      - jinja2==3.1.4
      - joblib==1.4.2
      - kaleido==0.2.1
      - kiwisolver==1.4.5
      - kornia==0.6.7
      - lightning-utilities==0.11.2
      - llvmlite==0.42.0
      - loguru==0.7.2
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess
      - networkx==3.3
      - numba
      - numpy==1.26.4
      - omegaconf==2.3.0
      - pandas==2.2.2
      - pillow==10.3.0
      - pip==24.3.1
      - plotly==5.22.0
      - protobuf==5.27.0
      - pyinputplus==0.2.12
      - pyparsing==3.1.2
      - pysimplevalidate==0.2.12
      - pytorch-lightning==2.2.5
      - pytz==2024.1
      - pyyaml==6.0.1
      - requests==2.32.3
      - seaborn==0.13.2
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - sentry-sdk==2.5.1
      - setproctitle==1.3.3
      - setuptools==74.1.2
      - smmap==5.0.1
      - stdiomask==0.0.6
      - sympy==1.12.1
      - tenacity==8.3.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.5.0
      - torch==2.3.0
      - torchmetrics==1.4.0.post0
      - torchvision
      - tqdm==4.66.4
      - tslearn==0.6.3
      - tzdata==2024.1
      - urllib3==2.2.1
      - wandb==0.17.1
      - werkzeug==3.0.3
      - wheel==0.44.0
      - yarl==1.9.4
